app/modules/settings/forms.py
from flask_wtf import FlaskForm
from flask_babel import lazy_gettext as _l

from wtforms import PasswordField, SubmitField, EmailField
from wtforms.validators import DataRequired



class UserChangePasswordForm(FlaskForm):
    email = EmailField(_l('Email'))
    curr_password = PasswordField(_l('Your current password'), validators=[DataRequired()])
    new_password = PasswordField(_l('New password'), validators=[DataRequired()])
    submit = SubmitField(_l('Save'))

app/modules/settings/__init__.py
from flask import Blueprint

module = Blueprint('settings', __name__, url_prefix ='/settings')

from app.modules.settings import routes

app/modules/settings/routes.py
from datetime import datetime
import json

from flask import request, render_template, redirect, url_for
from flask_login import current_user, login_required
from flask_babel import lazy_gettext as _l

from app.models import User
from app import db, logger
from . import module
from .forms import UserChangePasswordForm


# Create a settings page
@module.route('/')
@login_required
def settings():
    try:
        history = json.loads(current_user.phone.history)
        history = {date: events for date, events in history.items() if events is not None}
        filtered = dict()
        for item in history.items():
            if datetime.strptime(item[0], '%Y.%m.%d') == datetime.strptime(datetime.strftime(datetime.now(), "%Y.%m.%d"), '%Y.%m.%d'):
                filtered[item[0]] = item[1]
        if not history:
            filtered = None
    except Exception as e:
        logger.error(f"Error fetching phone history for user {current_user.id}: {e}")
        filtered = None
    return render_template('settings/settings.html', title=_l('Settings'), history=filtered)


# Update user password
@module.route('/change_password/<int:id>', methods=['GET', 'POST'])
@login_required
def change_password(id: int):
    form = UserChangePasswordForm()
    try:
        user: User = current_user
        if request.method == 'GET':
            form.email.data = user.email

        elif form.validate_on_submit():
            if user.check_password(form.curr_password.data):
                user.set_password(form.new_password.data)
                db.session.commit()
                logger.debug(f"Password successfully changed for user {user.id}")
                return redirect(url_for('settings.settings'))
            else:
                form.email.data = user.email
                return render_template('settings/change_password.html', title=_l('Your Profile'), form=form, message=_l('Incorrect current password.'))

    except Exception as e:
        logger.error(f"Error changing password for user {id}: {e}")
        db.session.rollback()
        return render_template('settings/change_password.html', title=_l('Your Profile'), form=form, message=_l('Error, please retry.'))

    return render_template('settings/change_password.html', title=_l('Your Profile'), form=form)

app/templates/settings/change_password.html
{% extends "base.html" %}

{% block content %}
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
</head>
<body class="d-flex align-items-center py-4 bg-body-tertiary">
<main class="form-signin w-100 m-auto">
  <form action="" method="post">
    {{ form.hidden_tag() }}
    <a href="/"><img src="{{ url_for('static', filename='img/base/logo.png') }}" width="180px"></a>
    <h1 class="mb-4 mt-4 text1">{{ _('Password Reset') }}</h1> <!-- Use translation function -->

    <div class="form-floating">
        {{ form.email(type="email", class="form-control", id="floatingInput", placeholder="name@example.com", disabled=field_disabled) }}
        <label for="floatingInput">{{ _('Email') }}</label>
        {% for error in form.email.errors %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endfor %}
    </div>

    <div class="form-floating">
        {{ form.curr_password(type="password", class="form-control", id="floatingPassword", placeholder="{{ _('Current Password') }}") }}
        <label for="floatingPassword">{{ _('Current Password') }}</label>
        {% for error in form.curr_password.errors %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endfor %}
    </div>

    <hr style="width: 90%; height: 2px; display: flex; margin: 10px auto;">

    <div class="form-floating" style="margin-top: 10px;">
        {{ form.new_password(type="password", class="form-control", id="floatingNewPassword", placeholder="{{ _('New Password') }}") }}
        <label for="floatingNewPassword">{{ _('New Password') }}</label>
        {% for error in form.new_password.errors %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endfor %}
    </div>

    <p style="margin-top: 10px;">{{ form.submit(class="btn btn-primary w-100 py-2 fs-5 fw-bold", type="submit", value=_('Submit')) }}</p>
    <div>{{ message }}</div>
  </form>
</main>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
{% endblock %}

app/templates/settings/settings.html
{% extends "base.html" %}

{% block content %}
<head>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/phone.css') }}">
</head>
<div class="container">
    <div class="profile-header">
        <h1 class="text-center mt-5 mb-4">{{ _('Profile Settings') }}</h1>
    </div>

    <div class="d-flex flex-column flex-lg-row justify-content-between">
        <div class="profile-info p-4 border rounded shadow-sm bg-light mb-4 mb-lg-0" style="flex: 1; margin: 1rem; height: 125%;">
            <div class="mb-4">
                <h2>{{ _('Name:') }}</h2>
                <p class="fs-4">{{ current_user.name }}</p>
            </div>
            <div class="mb-4">
                <h2>{{ _('Surname:') }}</h2>
                <p class="fs-4">{{ current_user.surname }}</p>
            </div>
            <div class="mb-4">
                <h2>{{ _('Date of Birth:') }}</h2>
                <p class="fs-4">{{ current_user.date_of_birth }}</p>
            </div>
            <div class="mb-4">
                <h2>{{ _('Email:') }}</h2>
                <p class="fs-4">{{ current_user.email }}</p>
            </div>
            <div class="text-center">
                <a href="{{ url_for('settings.change_password', id=current_user.id) }}" class="btn btn-danger" style="background-color:#c26381; color: white;">{{ _('Change password') }}</a>
                <a href="{{ url_for('register.logout') }}" style="background-color:white; color: black;" class="btn btn-secondary">{{ _('Log out') }}</a>
            </div>
        </div>

        <div class="profile-info p-4 border rounded shadow-sm bg-light" style="flex: 1; margin: 1rem; z-index: -1000;">
            <h2 class="text-center">{{ _('Today\'s phone history') }}</h2>
            {% if history %}
                <div class="timeline timeline-today">
                    {% for events in history.values() %}
                        {% for event in events %}
                        <div class="timeline-item">
                            <div class="timeline-content">
                                <div class="time-record">
                                    <span class="date">{{ event[1].split(' ')[0] }}</span>
                                    <span class="time">{{ event[1].split(' ')[1] }}</span>
                                </div>
                                <h5 style="color:#5c5555">{{ _('Return phone!') if event[0] else _('Put phone in device!') }}</h5>
                            </div>
                        </div>
                        {% endfor %}
                    {% endfor %}
                </div>
            {% else %}
                <h1 class="nothing" style="font-size: 1.8rem; text-align: center;">{{ _('You haven\'t got phone history!') }}</h1>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}