app/modules/register/forms.py
from flask_wtf import FlaskForm
from flask_babel import lazy_gettext as _l

from wtforms import PasswordField, BooleanField, SubmitField, EmailField, StringField, DateField
from wtforms.validators import DataRequired, Email, Length, EqualTo


class LoginForm(FlaskForm):
    email = EmailField(_l('Email'), validators=[DataRequired(), Email()])
    password = PasswordField(_l('Password'), validators=[DataRequired()])
    remember_me = BooleanField(_l('Remember me'))
    submit = SubmitField(_l('Log in'))


class RegisterForm(FlaskForm):
    name = StringField(_l('Your name'), validators=[DataRequired()])
    surname = StringField(_l('Your surname'), validators=[DataRequired()])
    date_of_birth = DateField(_l('Date'), validators=[DataRequired()])
    email = EmailField(_l('Email'), validators=[DataRequired(), Email(message=None), Length(min=6, max=40)])
    password = PasswordField(_l('Password'), validators=[DataRequired(), Length(min=6, max=40)])
    password_again = PasswordField(_l('Repeat password'), validators=[DataRequired(),
        EqualTo("password", message=_l("Passwords are different."))])
    submit = SubmitField(_l('Sign up'))

app/modules/register/__init__.py
from flask import Blueprint

module = Blueprint('register', __name__, url_prefix ='/register')

from app.modules.register import routes

app/modules/register/routes.py
from flask import render_template, make_response, redirect, url_for, request
from flask_login import login_user, login_required, logout_user, current_user
from flask_babel import lazy_gettext as _l

from app.models import User
from app import db, logger
from . import module
from .forms import RegisterForm, LoginForm


# Registration user profile
@module.route('/register', methods=['POST', 'GET'])
def register():
    if current_user.is_authenticated:
        return make_response(redirect(url_for('settings.settings')))

    form = RegisterForm()
    if form.validate_on_submit():
        logger.debug(f"Processing registration form for email: {form.email.data}")
        if form.password.data != form.password_again.data:
            return render_template('register/register.html', title=_l('Sign Up'), form=form,
                                   message=_l('Passwords are different!'))
        if User.query.filter_by(email=form.email.data).first():
            return render_template('register/register.html', title=_l('Sign Up'), form=form,
                                   message=_l('User already exists'))

        try:
            user = User(
                name=form.name.data,
                surname=form.surname.data,
                date_of_birth=form.date_of_birth.data,
                email=form.email.data,
                utc=request.cookies.get('timezone')
            )
            user.set_password(form.password.data)
            db.session.add(user)
            db.session.commit()
            logger.info(f"User {form.email.data} successfully registered.")
            return redirect(url_for('register.login'))
        except Exception as e:
            logger.error(f"Error registering user with email {form.email.data}: {e}")
            db.session.rollback()
            return render_template('register/register.html', title=_l('Registration'), form=form,
                                   message=_l('An error occurred during registration.'))

    return render_template('register/register.html', title=_l('Registration'), form=form)


# Logging
@module.route('/login', methods=['POST', 'GET'])
def login():
    if current_user.is_authenticated:
        return make_response(redirect(url_for('settings.settings')))

    form = LoginForm()
    if form.validate_on_submit():
        logger.debug(f"Processing login form for email: {form.email.data}")
        try:
            user = User.query.filter_by(email=form.email.data).first()
            if user and user.check_password(form.password.data):
                login_user(user, remember=form.remember_me.data)
                response = make_response(redirect(url_for('settings.settings')))
                return response

            return render_template('register/login.html', title=_l('Sign In'), message=_l('Mistake in login or password'),
                                   form=form)
        except Exception as e:
            logger.error(f"Error during login: {e}")
            return render_template('register/login.html', title=_l('Sign Up'), form=form,
                                   message=_l('Error in authorization.'))

    return render_template('register/login.html', title=_l('Authorization'), form=form)


# Logout
@module.route('/logout')
@login_required
def logout():
    logout_user()
    response = make_response(redirect(url_for('main.main')))
    response.set_cookie('username', '', expires=0)

    return response

app/templates/register/login.html
<!doctype html>
<html lang="{{ g.locale }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
</head>
<body class="d-flex align-items-center py-4 bg-body-tertiary">
<main class="form-signin w-100 m-auto">
  <form action="" method="post">
    {{ form.hidden_tag() }}
    <a href="/"><img src="{{ url_for('static', filename='img/base/logo.png') }}" class="mt-4" width="200px" alt="Logo"></a>
    <h1 class="mb-4 mt-4 text1">{{ _('Log In') }}</h1>

    <div class="form-floating mb-3">
        {{ form.email(class="form-control", id="floatingEmail", placeholder=_('name@example.com'), autocomplete="email") }}
        <label for="floatingEmail">{{ _('Email') }}</label>
        {% for error in form.email.errors %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endfor %}
    </div>

    <div class="form-floating mb-3">
        {{ form.password(class="form-control", id="floatingPassword", placeholder=_('Password'), autocomplete="current-password") }}
        <label for="floatingPassword">{{ _('Password') }}</label>
        {% for error in form.password.errors %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endfor %}
    </div>

    <p style="margin: 10px;">{{ form.remember_me() }} {{ form.remember_me.label }}</p>

    <button class="btn btn-primary w-100 py-2 fs-5 fw-bold" type="submit">{{ _('Sign In') }}</button>

    <p class="mt-3">{{ _('Don\'t have an account?') }} <a href="{{ url_for('register.register') }}" class="fw-bold" style="text-decoration: none; color: #dd458d;">{{ _('Sign Up') }}</a></p>

    <div>{{ message }}</div>
  </form>
</main>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

app/templates/register/register.html
<!doctype html>
<html lang="{{ g.locale }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
</head>
<body class="d-flex align-items-center py-4 bg-light">
<main class="form-signin w-100 m-auto">
  <form action="" method="post" lang="{{ g.locale }}">
    {{ form.hidden_tag() }}
    <a href="/" class="logo-container"><img src="{{ url_for('static', filename='img/base/logo.png') }}" class="mt-4" width="180px"></a>
    <h1 class="mb-4 mt-4 text1">{{ _('Sign Up') }}</h1>

    <div class="form-floating mb-3">
        {{ form.name(class="form-control", id="floatingName", placeholder=_('Name')) }}
        <label for="floatingName">{{ _('Your name') }}</label>
        {% for error in form.name.errors %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endfor %}
    </div>

    <div class="form-floating mb-3">
        {{ form.surname(class="form-control", id="floatingSurname", placeholder=_('Surname')) }}
        <label for="floatingSurname">{{ _('Your surname') }}</label>
        {% for error in form.surname.errors %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endfor %}
    </div>

    <div class="form-floating mb-3">
        {{ form.date_of_birth(class="form-control", id="floatingDate", placeholder=_('mm/dd/yyyy')) }}
        <label for="floatingDate">{{ _('Your date of birth') }}</label>
        {% for error in form.date_of_birth.errors %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endfor %}
    </div>

    <div class="form-floating mb-3">
        {{ form.email(class="form-control", id="floatingEmail", placeholder=_('name@example.com')) }}
        <label for="floatingEmail">{{ _('Email') }}</label>
        {% for error in form.email.errors %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endfor %}
    </div>

    <div class="form-floating mb-3">
        {{ form.password(class="form-control", id="floatingPassword", placeholder=_('Password')) }}
        <label for="floatingPassword">{{ _('Password') }}</label>
        {% for error in form.password.errors %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endfor %}
    </div>

    <div class="form-floating mb-3">
        {{ form.password_again(class="form-control", id="floatingPasswordAgain", placeholder=_('Password again')) }}
        <label for="floatingPasswordAgain">{{ _('Repeat password') }}</label>
        {% for error in form.password_again.errors %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endfor %}
    </div>

    <p>{{ form.submit(class="btn btn-primary w-100 py-2 fs-5 fw-bold mt-3", type="submit") }}</p>

    <p>{{ _('Have an account?') }} <a href="{{ url_for('register.login') }}" class="fw-bold login-link">{{ _('Log In') }}</a></p>
    <div>{{ message }}</div>
  </form>
</main>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>